### ISSUE TITLE
Bump upper bound on ghc-mod

### ISSUE THREAD

**Issue by snoyberg** [mvoidex/hsdev#10]
The current upper bound is overly restrictive, and prevent hsdev from working with Stackage. I just tested, and the upper bound can be relaxed. I'd send a pull request, but it seems like your master branch has already removed the upper bound.

Pinging @geraldus, original issue: https://github.com/fpco/stackage-server/issues/50

By the way, can I recommend [adding your package to Stackage](https://github.com/fpco/stackage#get-your-package-included) so that you'll be notified of breakage and users can more easily use your package?

**Comment by mvoidex** [comment]
Created PR https://github.com/fpco/stackage/pull/393
