### ISSUE TITLE
Problem installing on macOS BigSur (Cocoa not found)

### ISSUE THREAD

**Issue by nikita-volkov** [mvoidex/hsdev#105]
```
[11 of 76] Compiling HsDev.Database.SQLite.Schema ( src/HsDev/Database/SQLite/Schema.hs, dist/build/HsDev/Database/SQLite/Schema.o, dist/build/HsDev/Database/SQLite/Schema.dyn_o )
<command line>: can't load framework: Cocoa (not found)
cabal: Failed to build hsdev-0.3.4.0 (which is required by exe:hsdev from
hsdev-0.3.4.0). See the build log above for details.
```

OS Version: 11.0.1

**Comment by mvoidex** [comment]
`hsdev` doesn't depend on cocoa directly. I've found similar issue: https://gitlab.haskell.org/ghc/ghc/-/issues/18592
I also have no mac, so have no idea how to reproduce and fix it.

Note, that `hsdev` is no longer actively developed. Better option may be using [Haskell Language Server](https://github.com/haskell/haskell-language-server)

**Comment by nikita-volkov** [comment]
Thanks
