### ISSUE TITLE
Invalid Haddock syntax in hsdev-0.1.3.3

### ISSUE THREAD

**Issue by peti** [mvoidex/hsdev#11]
src/HsDev/Database/Update.hs:303:9:
        parse error on input ‘-- ^ Read data from cache
    ’

See http://hydra.cryp.to/build/502397/nixlog/2/raw for a complete build log.

**Comment by peti** [comment]
Would you care to share the reason for suddenly closing this issue after 1 year of inactivity?

**Comment by mvoidex** [comment]
Sure
Log is no more accesible.
`cabal haddock` doesn't return any errors and docs seems to be ok (this doc is present on [hackage](http://hackage.haskell.org/package/hsdev-0.2.1.0/docs/HsDev-Database-Update.html#v:scan))
If I misunderstood something, feel free to reopen issue and, if possible, provide additional info
