### ISSUE TITLE
ghc-mod type "File not found"

### ISSUE THREAD

**Issue by s-trooper** [mvoidex/hsdev#14]
Hi, 
i send follow request:
{"id": "5", "opts": {"file": "C:/Dev/hs/Main.hs"}, "command": "ghc-mod type", "args": ["5", "2"]}

and got response:
3:{"error":"File 'C:\\Dev\\hs\\Main.hs' not found","details":{}}

the problem is "ghc-mod type C:/Dev/hs/Main.hs 5 2" work so what i do wrong?

**Comment by mvoidex** [comment]
File must be scanned before using with any commands.

    ⋘ {"command":"scan","opts":{"file":"Test.hs","silent":null}} -- `silent` if don't want to get notifications about scan progress
    ⋙ 1:{"result":[]}
    ⋘ {"command":"ghc-mod type","opts":{"file":"Test2.hs"},"args":["12","6"]}
    ⋙ 2:{"result":[{"expr":"x","region":{"to":{"line":12,"column":7},"from":{"line":12,"column":6}},"type":"Int"},{"expr":"test x = x","region":{"to":{"line":12,"column":11},"from":{"line":12,"column":1}},"type":"Int -> Int"}]}

Maybe I'll remove this condition later or add flag '--auto-scan'.

Note, that scan will scan docs and infer types by default, which is not fast (specially infer), therefore you may want to specify flags '--no-docs' and/or '--no-infer'. Anyway, file will be available for using right after source scan and before docs scan/type infer.

**Comment by mvoidex** [comment]
> Note, that scan will scan docs and infer types by default
I've changed this, because docs&infer takes much time. So it's now disabled by default.

> Maybe I'll remove this condition later or add flag '--auto-scan'
Do you need this option?

Please, close issue, if you think, that it's resolved

**Comment by mvoidex** [comment]
I'll close it
