### ISSUE TITLE
ghc-mod 5.2.1.3 is not yet available

### ISSUE THREAD

**Issue by MorrisFeist** [mvoidex/hsdev#17]
I guess its a typo and it should be 5.2.1.2 instead?

**Comment by mvoidex** [comment]
Its not a typo, it uses [ghc-mod](https://github.com/kazu-yamamoto/ghc-mod) from GitHub (which has version `0`), which is not released yet

**Comment by MorrisFeist** [comment]
Ah ok, nevermind then, thank you
