### ISSUE TITLE
Does not compile with ghc-mod-5.4.0.0

### ISSUE THREAD

**Issue by crockeea** [mvoidex/hsdev#20]
As the title says, I cannot build hsdev with ghc-mod-5.4.0.0, and the current release of hsdev on hackage does not constrain to use ghc-mod-5.3.0.0.

**Comment by lspitzner** [comment]
Bump. That is why upper bounds are cool. To fix this, you'd have to retroactively add upper bounds to all (/most) versions on hackage.

**Comment by mvoidex** [comment]
I've updated package info on hackage, now it have `ghc-mod >= 5.3.0.0 && < 5.4.0.0` constaint

**Comment by lspitzner** [comment]
On ghc-7.8.4 my --dry-run reports that it would install 0.1.3.4 of hsdev and 5.4.0.0 of ghc-mod. I'd strongly assume that this would break in the same way as it did for ghc-7.10.2.

**Comment by polygonhell** [comment]
Doesn't work for me even explicitly installing hsdev-0.1.4.3
It tries to install ghc-mod-5.3.0 which apparently no longer builds either

**Comment by etairi** [comment]
It should work now, try `cabal update` and then `cabal install hsdev`, it will also install `ghc-mod-5.3.0.0`. The was a problem with the upper bound of a dependency. It has been [fixed](http://hackage.haskell.org/package/ghc-mod-5.3.0.0/revisions/) now.

**Comment by mvoidex** [comment]
Should work now with new version

**Comment by lspitzner** [comment]
looks good, thanks!
