### ISSUE TITLE
Compilation errors (hsdev-0.1.5.1)

### ISSUE THREAD

**Issue by cmahon** [mvoidex/hsdev#21]
[27 of 55] Compiling HsDev.Inspect    ( src/HsDev/Inspect.hs, dist/build/HsDev/Inspect.o )

src/HsDev/Inspect.hs:112:13:
    Constructor ‘H.EVar’ should have 2 arguments, but has been given 1
    In the pattern: H.EVar n
    In an equation for ‘getExports’:
        getExports (H.EVar n)
          = [uncurry ExportName (identOfQName n) ExportNothing]

src/HsDev/Inspect.hs:213:55:
    Couldn't match type ‘H.Binds’ with ‘Maybe H.Binds’
    Expected type: H.Match -> Maybe H.Binds
      Actual type: H.Match -> H.Binds
    In the second argument of ‘(.)’, namely ‘matchBinds’
    In the first argument of ‘concatMap’, namely
      ‘(getBinds . matchBinds)’

src/HsDev/Inspect.hs:215:121:
    Couldn't match expected type ‘Maybe H.Binds’
                with actual type ‘H.Binds’
    In the first argument of ‘getBinds’, namely ‘binds’
    In the second argument of ‘Function’, namely ‘(getBinds binds)’

**Comment by mvoidex** [comment]
Fixed `haskell-src-exts` constraint on hackage

**Comment by cmahon** [comment]
Thanks a lot for the quick response, compiles fine now.
