### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by kolmodin** [mvoidex/hsdev#24]
It seems that hsdev is not part of stackage. Is there a good reason why it's not?

**Comment by mvoidex** [comment]
It was, but then was removed (https://github.com/fpco/stackage/issues/778)
I'll make pull request soon

**Comment by mvoidex** [comment]
https://github.com/fpco/stackage/pull/1206

**Comment by kolmodin** [comment]
Awesome, thanks!
Is it likely that hsdev will be excluded from stackage again? I'm considering whether we could use `stack` to install all required tools for SublimeHaskell.

**Comment by mvoidex** [comment]
I think it won't be excluded
The problem was that i've used ghc-mod from github so that hsdev can't be installed using ghc-mod from hackage.

**Comment by kolmodin** [comment]
OK, great!

**Comment by m4lvin** [comment]
Could hsdev also be added to LTS haskell again? (Sorry if this is the wrong place to ask...) It was in 6.22 but since then is missing. Right now I have to do "stack --resolver nightly-2016-10-18 install hsdev" to get it installed.

**Comment by mvoidex** [comment]
@m4lvin, unfortunately, i don't know anything about stackage politics, so i can't say if it can be added to released LTS versions
