### ISSUE TITLE
hsdev check failed

### ISSUE THREAD

**Issue by AlexKovalevych** [mvoidex/hsdev#28]
$ hsdev check --file test.hs --pretty
{
    "error": "Could not find module ‘Prelude’\nIt is a member of the hidden package ‘base-4.8.2.0’.\nUse -v to see a list of the files searched for.\n",
    "details": {}
}

I've installed haskell platform for osx and hsdev-0.1.7.3, (ghc 7.10.3)

Not sure how to fix that, please help.

**Comment by mvoidex** [comment]
Can you try `hsdev-0.1.8.2`?

**Comment by AlexKovalevych** [comment]
Yes, it works fine with 0.1.8.2, closing the issue.
