### ISSUE TITLE
cabal install on mac os failed.

### ISSUE THREAD

**Issue by godsme** [mvoidex/hsdev#30]
src/HsDev/Util.hs:272:58: error:
    • Variable not in scope:
        (<>) :: Parser (a0 -> a0) -> Mod f0 a1 -> t1
    • Perhaps you meant one of these:
        ‘<|>’ (imported from Options.Applicative),
        ‘</>’ (imported from System.FilePath),
        ‘<$>’ (imported from Options.Applicative)

src/HsDev/Util.hs:272:71: error:
    • Variable not in scope: (<>) :: t1 -> Mod f1 a2 -> t0
    • Perhaps you meant one of these:
        ‘<|>’ (imported from Options.Applicative),
        ‘</>’ (imported from System.FilePath),
        ‘<$>’ (imported from Options.Applicative)

src/HsDev/Util.hs:272:91: error:
    • Variable not in scope: (<>) :: t0 -> Mod f2 a3 -> t
    • Perhaps you meant one of these:
        ‘<|>’ (imported from Options.Applicative),
        ‘</>’ (imported from System.FilePath),
        ‘<$>’ (imported from Options.Applicative)

**Comment by mvoidex** [comment]
since 0.13 `optparse-applicative` doesn't reexport `(<>)`
I've edited `hsdev.cabal` on hackage to depend on `>= 0.11 && < 0.13` version of `optparse-applicative`, try it (`cabal update`, `cabal install hsdev`)

**Comment by mvoidex** [comment]
I'll close this issue. Reopen if it still fails to install.
