### ISSUE TITLE
recursive directory problem, hsdev is stuck

### ISSUE THREAD

**Issue by reygoch** [mvoidex/hsdev#36]
My team uses specific project structure, for example, we have a dir (not a project dir, just a regular one) like this :

```
ProjectDirectory
+ Module01
 |- .local
+ Module02
 |- .local
+ Module03
 |- .local
...
```

This `.local` folder is symbolic link to `ProjectDirectory` so that we can import e.g. `Module01` into `Module02`.

I don't know why exactly it was done in such a way, but `hsdev` seems to get stuck in a loop with this case, and I can't use `SublimeHaskell` because `hsdev` gets stuck inspecting my project for ever.

If I remove `.local` symlink, than I get back intellisense, but when I save project I constantly get errors like this `Sublime Haskell: hsdev types returns error: ghc error, msg: Failed to load interface for 'Module01'`.

And I obviously can't build my module.

**Comment by mvoidex** [comment]
That's because I traverse directories by simply using `getDirectoryContents`.
I can ignore symbolic link, is it reasonable behaviour?

**Comment by reygoch** [comment]
I guess it could be, things behave normally in Atom with ghc-mod so I'm assuming they have taken a different approach?

**Comment by mvoidex** [comment]
I'm not sure that `ghc-mod` traverses directories depthward.
I'll ignore symbolic link

**Comment by reygoch** [comment]
Yes, most likely. Although, will intellisense for module from .local work in that case? It does in Atom.

**Comment by mvoidex** [comment]
Not sure that it will work in current implementation, so i have to take care about it.
`ghc-mod` uses `ghc` to resolve symbols

let me ask questions to gain clarity, i'm not sure, that i correctly understood your case with sym links.

`Module01` - folder? If not, then where is `.local` placed? If yes, then where is module `Module01`?

**Comment by reygoch** [comment]
Ye, I've missnamed it a bit.

So `ProjectDirectory` is just a plain old folder in which we hold all of our `stack projects / modules`.

`.local` is a symlink to ProjectDirectory and it's placed in all `Module` project folders so that each `Module` has access to every other Module, including it self (thus symlink loop).

Apparently that is 'flexible' as I was explained.

**Comment by mvoidex** [comment]
Ah, I see. Smth like this:

```
Root
+ Module1
|- Quux.hs
|- Foo.hs // import Module2.Bar
|- .local
+ Module2
|- Bar.hs // import Module1.Quux
|- .local
```

**Comment by reygoch** [comment]
Yes, exactly!

**Comment by reygoch** [comment]
Just to give an update on this issue. How it actually currently works with ghc-mod is that (I'm guessing) symbolic links are ignored unless packages are explicitly listed in stack.yml e.g. :

```
packages:
- .
- .local/basic
- .local/settings
```

**Comment by mvoidex** [comment]
Thanks for ping. I'll try to take a look in early january

**Comment by mvoidex** [comment]
@reygoch, i've added check for symbolic link, can you try it?

**Comment by mvoidex** [comment]
Feel free to reopen if issue is still here
