### ISSUE TITLE
hsdev check: Could not find module

### ISSUE THREAD

**Issue by adamschoenemann** [mvoidex/hsdev#37]
I am trying to use hsdev 0.2.1.0 with a stack project. Everything works fine with stack/cabal. But it seems like hsdev is not picking up the packages mentioned in `build-depends` in my `.cabal` file - it always only searches `base`, and in this case I am using a monad transformer from `mtl`, and other packages. Perhaps I am missing something? `hsdev scan -p .` does seem to pick up the projects and some package indices.

**Comment by mvoidex** [comment]
Are you using `hsdev` or `SublimeHaskell`?

How do you detect that hsdev is not picking these packages?
Could you provide minimal sequence of `hsdev` commands which shows issue?

**Comment by adamschoenemann** [comment]
The goal is to have `SublimeHaskell` working, `hsdev` is what is causing the errors, since they appear using both `SublimeHaskell` and using `hsdev` manually.

`hsdev` will find modules in my src code fine, and also from `base` and apparently `containers`, but not e.g. `mtl` and `pretty`. So it seems to only search the packages included with GHC, maybe? I'm certainly no expert. 

The error happens with `SublimeHaskell` and `hsdev`. I've tried doing `hsdev scan --path .` and it seems to pick up package dbs in both .stack-work and `$STACK_ROOT`, but `check` still reports the error.

**Comment by mvoidex** [comment]
Sorry for delay, i have no time last months.

Could you some minimal test project, which still shows issue, so that i will be able to reproduce this error?

**Comment by adamschoenemann** [comment]
Here is a link: https://github.com/adamschoenemann/hsdev-test

I also seem to get this error everytime i save a file (with SublimeHaskell)

    hsdev types returns error: module not inspected, id: 16, module: {'project': None, 'file': 'F:\\Projects\\haskell\\hsdev-test\\hsdev-test.cabal'}

I'm on windows 10 with stack 1.2.0.
Any other info you need?

**Comment by mvoidex** [comment]
Thanks! I'll try to get into this weekend.

Do you have project folder added to sublimetext project folders or you just opens some .hs?
You have no `Control.Monad.State` completions in https://github.com/adamschoenemann/hsdev-test/blob/master/src/Lib.hs, right?

**Comment by adamschoenemann** [comment]
Great! Thanks for the swift response.
I usually open it with `subl .` so the folder is added as the root of the project in Sublime.
You are correct - I don't have any `Control.Monad.State` completions.

**Comment by mvoidex** [comment]
I've located bug, will try fix as soon as possible.

**Comment by adamschoenemann** [comment]
Cool, looking forward to it!

**Comment by ruslantalpa** [comment]
@mvoidex if you could briefly explain the bug and point to it's location, i would try and see if i can fix it.

**Comment by mvoidex** [comment]
@ruslantalpa thanks, I'll comment here some details i've found

**Comment by mvoidex** [comment]
@ruslantalpa 

When `hsdev` sees stack project, it asks `stack` for local and snapshot `package-db`s. For `hsdev-test` provided by @adamschoenemann i get this snapshot: `D:\stack\snapshots\e90768aa`.

There also function to scan modules within some `package-db`: https://github.com/mvoidex/hsdev/blob/master/src/HsDev/Database/Update.hs#L283

It passes all `package-db`s as flags for ghc, lists all modules (https://github.com/mvoidex/hsdev/blob/master/src/HsDev/Scan/Browse.hs#L67) and leaves only modules which located in top of `package-db`

In this dirty solution I assumed, that library is installed in folder where it is described (for example in my `D:\stack\snapshots\d114e2e9` path i have `pkgdb` with package descriptions and `lib` with installed packages), but it not true.

Snapshot `D:\stack\snapshots\e90768aa` have only `pkgdb` folder with description of `mtl` package, which itself installed in different folder: `D:\stack\snapshots\d114e2e9\lib` (and this path returned by `listModules` function), and therefore https://github.com/mvoidex/hsdev/blob/master/src/HsDev/Database/Update.hs#L286 filters this module out.

I think we can read `D:\stack\snapshots\e90768aa\pkgdb\mtl...conf` and get right path from there (it's in `library-dirs` section).

I hope i can get some time this weekend, but i'll be thankful for help.

**Comment by mvoidex** [comment]
> I think we can read D:\stack\snapshots\e90768aa\pkgdb\mtl...conf and get right path from there (it's in library-dirs section).

Seems, that it won't be enough. There is no quick fix of that, so i have to look into this closely.

**Comment by adamschoenemann** [comment]
Any update on this? :) Would be so awesome if this was fixed

**Comment by mvoidex** [comment]
In process :)
there's a need to refactor

**Comment by adamschoenemann** [comment]
Great to hear!
