### ISSUE TITLE
cabal "default-extensions" not passed to ghc during scan

### ISSUE THREAD

**Issue by bscottm** [mvoidex/hsdev#40]
I prefer to add "default-extensions" to my .cabal file so as not to pollute the top of my source files. However, it doesn't seem as if `hsdev` passes these options to `ghc` while scanning the source. As an example, `Utils.hs` requires OverloadedStrings:

    $ hsdev check -f src-emubase/Machine/MemorySystem.hs
    {"notify":[{"status":"working","progress":null,"name":".../emuwork/src-emubase/emubase.cabal","task":"scanning","type":"path"}]}
    {"notify":[{"status":"ok","progress":null,"name":".../emuwork/src-emubase/emubase.cabal","task":"scanning","type":"path"}]}
    {"notify":[{"status":"working","progress":null,"name":".../emuwork/src-emubase/Machine/MemorySystem.hs","task":"scanning","type":"module"}]}
    {"notify":[{"status":"ok","progress":null,"name":"...y/emuwork/src-emubase/Machine/MemorySystem.hs","task":"scanning","type":"module"}]}
    [{"note":{"suggestion":null,"message":"• Couldn't match expected type ‘Text’ with actual type ‘[Char]’\n• In the first argument of ‘append’, namely ‘\"0x\"’\n  In the first argument of ‘(.)’, namely ‘append \"0x\"’\n  In the expression: append \"0x\" . asHex"},"source":{"project":null,"file":".../emuwork/src-emubase/Machine/Utils.hs"},"region":{"to":{"line":27,"column":26},"from":{"line":27,"column":22}},"level":"error"}, ...]

'OverloadedStrings' is specified in the `emubase.cabal` file in the Library to which this code snippet belongs.

The `hsdev check` will work if I put `{-# LANGUAGE OverloadedStrings #-}` at the top of the source. Not quite sure where to look in the source to start figuring out how to debug and propose a patch. Happy to look at the problem and propose a patch if you can give me a bit of clue.

**Comment by mvoidex** [comment]
Thanks for your readiness to help. There was stupid bug: `.` (from `source-dirs`) was not recognised as parent for any other file. Fixed and added simple test for it (https://github.com/mvoidex/hsdev/blob/master/tests/Test.hs#L44)
It's not on hackage yet (there's another bug i want to fix before), but you can clone & build.

**Comment by bscottm** [comment]
Thanks! Will give it a try... :-)

**Comment by bscottm** [comment]
Just started to test, ran into "new" issue, which I'm trying to trace down. Sequence of events:

    $ cd src-directory
    $ hsdev start
    Server started at port 4567
    $ hsdev complete -f Foo.hs
    Missing:

    Usage: hsdev complete [-w|--wide] (-f|--file path)
      show completions for input

**Comment by bscottm** [comment]
I did a bit more digging and recovered the log file from SublimeHaskell. For some reason, `hsdev` gets a lot of these messages:

    13/01/17 19:03:40 -0800 ERROR   33/check> Scope leaves with exception: ghc exception: <stderr>: hPutChar: resource vanished (Broken pipe)

[Log file](https://github.com/mvoidex/hsdev/files/705719/hsdev.txt) attached. Again, point me in a direction and maybe I can diagnose further.

**Comment by bscottm** [comment]
Oh. Wait a second. I'm blind. The log file is telling me that the "stack" command to get the compiler path failed, so `hsdev` is trying to execute `ghc`, which will naturally fail on my system. I think I know where to look in your commits.

**Comment by bscottm** [comment]
@mvoidex: Disregard. Moved this thread to another ticket.
