### ISSUE TITLE
Is there a pre-built Windows hsdev.exe binary?

### ISSUE THREAD

**Issue by metaleap** [mvoidex/hsdev#41]
Doesn't build at my end "the simple way" (`stack install hsdev`), tried [this hack](http://stackoverflow.com/questions/36526978/failure-to-install-hsev-on-windows-10-via-stack-install-hsdev#36528910) and failed, no amount of tinkering and tweaking amounted to much here, almost ready to give up (not exactly mission-critical though _supremely_ nice-to-have no less) but _would_ love to have a hsdev.exe in my local\bin so SublimeHaskell gets a little boost --- so since I'm not seeing a website or user forum for hsdev I'm asking right, in case any Windows user has this sitting around compiled and working-just-fine..

**Comment by mvoidex** [comment]
I'm using cabal

Here's my binary
https://1drv.ms/u/s!Amfc7blJLA9m6bRO-tsh6_p5v5Zr9w

**Comment by metaleap** [comment]
Marvellous, many thanks!

**Comment by metaleap** [comment]
So somehow hsdev expects my local Programs folder to contain a ghc folder.. guess this is something I should poke the SublimeHaskell folks about?

    Sublime Haskell: hsdev ping: no pong
    Sublime Haskell: Starting hsdev server
    Sublime Haskell: hsdev server started at port 4567
    Sublime Haskell: connecting to hsdev server (0)...Sublime Haskell: connecting to hsdev server (0)...

    Sublime Haskell: connected to hsdev serverSublime Haskell: connected to hsdev server

    Sublime Haskell: hsdev types returns error: ghc error, msg: D:\Programs\ghc\ghc-8\lib\settings: openFile: does not exist (No such file or directory), id: 3
    Sublime Haskell: hsdev module returns error: module not inspected, module: {'project': None, 'file': 'D:\\dev\\hs\\hax2\\Util.hs'}, id: 8
    Sublime Haskell: hsdev module returns error: module not inspected, module: {'project': None, 'file': 'D:\\dev\\hs\\hax2\\Pages.hs'}, id: 12

**Comment by mvoidex** [comment]
Wow
This is my ghc folder.
GHC is initialized with `libdir` from `ghc-paths`, and seems that it is hardcoded when `ghc-paths` is installed:
http://hackage.haskell.org/package/ghc-paths-0.1.0.9/docs/src/GHC-Paths.html#libdir

hsdev should detect ghc installation folder (or accept some flag) instead of using libdir
i'll try to fix it tomorrow

**Comment by metaleap** [comment]
Argh did you reply just as I deleted that comment  ;)  thx anyway! Just to get going I copied my ghc from stack folders to my Programs folder brute-forcey, but SH still can't seem to get any mileage out of hsdev other than starting the server .. ah well, back to actual programming for now, there's no telling how much the deeper this rabbit hole will go hehe

**Comment by metaleap** [comment]
Well now apparently that everything was scanned it works pretty niftily indeed! Much awesome here. I take it you're involved with SH as well as hsdev --- ever wanted to assign a key binding to "open REPL on current module file in my ST3's adjacent layout column (or row)"? Haven't figured out how to achieve this if even possible, in the keybindingsmap file nothing of this sort shows up searching for repl or ghci. But---not the most important thing in the world, this. Great project once it's up & running, thanks for the binary again!

**Comment by mvoidex** [comment]
> "open REPL on current module file in my ST3's adjacent layout column (or row)"

I'm using this combo:
1. Ctrl+P: one of `SublimeHaskell Repl` commands: `GHCi`, `GHCi current file`, `Cabal repl`, `Load` (same as `GHCi current file` or `Cabal repl` depending on opened file).
2. `Ctrl+K`, `up` - splits vertically

**Comment by metaleap** [comment]
Yeah ctrl+P is actually good enough, no need for a keybinding, I'd totally forgot about this panel but now with SH working I'm actually finally starting to explore it

**Comment by mvoidex** [comment]
You also can make your key binding, command `Preferences: Key Bindings`:

	{
		"keys": ["ctrl+shift+1"], // just for example
		"command": "sublime_haskell_repl_load"
	},

**Comment by metaleap** [comment]
Works great thx for the pointer!
