### ISSUE TITLE
ghc> Scope leaves with exception: <stderr>: hPutChar: resource vanished (Broken pipe)

### ISSUE THREAD

**Issue by bscottm** [mvoidex/hsdev#42]
Testing based on current `hsdev` in github: I am trying to test the cabal-based GHC pragma fix that I reported earlier. My repo is a clone of yours, mvoidex/hsdev.

SublimeHaskell is completely unusable because the current `hsdev` reports this error for every request related to `ghc` (and others):

    ghc> Scope leaves with exception: <stderr>: hPutChar: resource vanished (Broken pipe)

This happens both on Windows and Mac OSX, so it's definitely independent of platform.

Cannot pin this down to a package change that `cabal` downloaded, although that seems the very likely culprit. It doesn't look like `hsdev` prematurely closes a file handle/descriptor and there are no recent changes in the commit log that would indicate this kind of problem.

Initially, I thought it might have to do with `runServerCommand` when it starts the `hsdev` server, which would narrow down the problem to changes in the `unix` package when running on Mac OSX. But the same issue happens on Win64, so I'm really at a loss for debugging.

Unsure how to track this down -- profiling?

SublimeHaskell log file (Win64): [hsdev.txt](https://github.com/mvoidex/hsdev/files/720692/hsdev.txt)

**Comment by mvoidex** [comment]
What's your ghc version?
This error can occur when ghc tries to print smth to stdout/stderr, but hsdev sets its own `log_action` (`src/HsDev/Tools/Ghc/Compat.hs:setLogAction`, used in `src/HsDev/Tools/Ghc/Worker.hs:ghcRun` and other ghc-related functions) to prevent writing directly to stdout/stderr (and also to parse errors/warnings from ghc).

I've built `hsdev` from `master` and this works ok:

    $ hsdev start
    $ hsdev scan --project hsdev
    ...
    $ hsdev check -f hsdev\src\HsDev\Server\Base.hs
    [{"note":{"suggestion":null,"message":"The import of `Packages' is redundant\n  except perhaps to import instances from `Packages'\n...

You can also attach to running server with `hsdev listen --config 'use trace'` to read log while it's running.

**Comment by bscottm** [comment]
Mine is the same, except that my `ghc` is `stack`-local.

So, I did a lot of debugging and was successfully able to figure this out. You cannot reproduce the bug with the command line tool. Why? Because the process' `stderr` is redirected to `/dev/null`.

The bug is really in SublimeHaskell: Comment out line 599 in `hsdev.py` -- you're closing the `stderr` side of the pipe to the `hsdev` process. That's the cause of all of the messages.

    diff --git a/hsdev.py b/hsdev.py
    index 2b74abd..81f4dcf 100644
    --- a/hsdev.py
    +++ b/hsdev.py
    @@ -596,7 +596,8 @@ class HsDev(object):
                 if m:
                     log('hsdev server started at port {0}'.format(m.group('port')))
                     p.stdout.close()
    -                p.stderr.close()
    +                # NOOOOO!!!! Dont do this!!!!
    +                # p.stderr.close()
                     return p
    
         # Socket functions

**Comment by bscottm** [comment]
Alternatively, you could have Python send the `hsdev` process' `stderr` to `/dev/null` instead of `subprocess.PIPE`.

**Comment by mvoidex** [comment]
Thanks for all your help!
Looking into it now.
Still can't reproduce it (win 10 x64), check doesn't produce these errors. I've also tried this:

    from subprocess import *
    p = Popen(['hsdev', 'run'], stdout=PIPE, stderr=PIPE, stdout=PIPE)
    p.stdout.close()
    p.stderr.close()

And from command line:

    hsdev scan --project .
    hsdev check -f src/...

No errors.

**Comment by bscottm** [comment]
I'm testing and diagnosing on Mac OSX -- *nix and *nix-like platforms. Also, you're testing against a test case that will succeed, i.e., one that doesn't have errors or output to `stderr`.

**Comment by mvoidex** [comment]
You said:

> This happens both on Windows and Mac OSX

Anyway, I'll try to test it on Ubuntu too.

> Also, you're testing against a test case that will succeed

What do you mean? I'm cheking file, which contains errors, and hsdev returns some errors or warnings, but it doesn't fail with broken pipe. Could you provide source of haskell module, which fails checking with hsdev for you?

**Comment by bscottm** [comment]
Think this through for a moment: If you close the `python` reader side of the pipe, where does the `hsdev` `stdout` and `stederr` writer's output go? The choice is up to the operating system -- in Mac OSX's case, the OS signals an error. MinGW under WinXX seems to do the same under some circumstances.

For me, your test case has the same output (no warnings, no errors) whether the pipe is closed or not. There are no warnings or errors generated, thus, no output and no error.

**Comment by mvoidex** [comment]
> If you close the python reader side of the pipe, where does the hsdev stdout and stederr writer's output go?

Well, hsdev doesn't write to stdout/stderr directly, it uses logger. In this case one of logger's thread which writes to stdout/stderr will just die and it's ok.

I understand the problem - ghc tries to write directly to stderr, which is closed, but ghc shouldn't do it as long as hsdev sets its own log_action. And I'm trying to understand when/how is it happened.

**Comment by bscottm** [comment]
Also, consider that you and I are running `hsdev` from a console/terminal, not from inside a window system, as Sublime is normally invoked.

Since all of `hsdev`'s child processes inherit the `stdout` and `stderr` file descriptors, it might be a good idea to do something defensive from within Sublime, such as redirect to `/dev/null` and not close them.

**Comment by bscottm** [comment]
Probably need to ensure that `ghc` sends it output to a temporary file. :-)

**Comment by bscottm** [comment]
In any case, I'll generate a patch for SublimeHaskell. That'll leave you some time to look at the pattern match fail. :-)

**Comment by mvoidex** [comment]
> it might be a good idea to do something defensive from within Sublime, such as redirect to /dev/null and not close them.

Yes, this may fix issue, but i'm still wondering, why ghc still writes to stderr :)

**Comment by bscottm** [comment]
Sent a pull request over on SublimeHaskell.

ghc writes to its parent process' stderr. You would probably need to `someFd \`dupTo\' stderr` to redirect it "properly". Haven't tested that theory yet, but it seems reasonable from my experience.

**Comment by mvoidex** [comment]
Ok, thanks, will review as soon as possible

**Comment by mvoidex** [comment]
> keep in mind that readProcess inherits the parent process' descriptors, except for stdin

As i understand, it inherits only stderr:

> readProcess forks an external process, reads its standard output strictly, blocking until the process terminates, and returns the output string. The external process inherits the standard error.

**Comment by mvoidex** [comment]
I've replaced `readProcess` with `readProcessWithExitCode` which doesn't inherit any handle.
Anyway, it's barely related to this issue - ghc runs in separate thread (it's not another process) and as i mentioned, shouldn't write to stderr.
Although your SublimeHaskell PR fixes it, I'll leave this issue open until I figure out why ghc writes to stderr.

**Comment by bscottm** [comment]
Looks like all issues addressed... on the hsdev and SublimeHaskell sides.
