### ISSUE TITLE
Why is hsdev using so much memory? 

### ISSUE THREAD

**Issue by moodmosaic** [mvoidex/hsdev#45]
While `ghc-mod` uses less than 250MB of memory, `hsdev` uses more than 1GB. Why?

![capture](https://cloud.githubusercontent.com/assets/287532/23017010/455ac41e-f441-11e6-9fe6-3e0381d37201.PNG)

Both in `ghc-mod` and `hsdev`, I used [this](https://static.charlieharvey.org.uk/writings/ReadXML.hs.txt) example which I found on Google, and I used Stack to build it.

---

Also, **when saving a file**, it looks like `hsdev` in SublimeHaskell is *much* slower than `ghc-mod`  in Atom/ide-haskell, at least when both are used with their default settings.

**Comment by mvoidex** [comment]
I haven't optimized memory consumption, but want to.
Main difference is that hsdev holds in memory info about installed modules and sources you're working on, so getting info should be fast (for example: `ctrl-I` on module name, or `browse module` command)

> Also, when saving a file, it looks like hsdev in SublimeHaskell is much slower than ghc-mod

Running `hsdev check -f ...` and `ghc-mod check ...` seems to take same amount of time for me. Atom may be much faster if it doesn't reinit ghc as hsdev does.

I'll try to compare with Atom (when I've tried atom, it didn't work well with my projects).

**Comment by cscherrer** [comment]
Calling `hsdev` via [SublimeHaskell](https://github.com/SublimeHaskell/SublimeHaskell) on a large project ([Hakaru](https://github.com/hakaru-dev/hakaru)) takes up all 16GB on my machine and freezes it. Any suggestions?

**Comment by mvoidex** [comment]
Wow
There's branch with reduced memory usage, but it's not integrated with SublimeHaskell.
I'll try to test it on this project.

**Comment by moodmosaic** [comment]
Looking forward to this, really, as this is a huge blocker for me 😕 For now I had to switch to Atom/ide-haskell/ghc-mod...

Once the memory consumption is optimized, I'll be switching back to ST3/SublimeHaskell/hsdev for sure.

**Comment by mvoidex** [comment]
@cscherrer, what version of hsdev do you have? Try to run hsdev alone (without starting SublimeHaskell) with these commands:

    hsdev start
    hsdev scan --cabal --project path/to/hakaru

Does it still uses so much memory? I've tried these commands on hsdev 0.2.5.0 and it takes 1GB

**Comment by cscherrer** [comment]
Ok I had used cabal-install, and it looks like it grabbed `hsdev-0.2.3.2`. I'll update and check it again

**Comment by cscherrer** [comment]
Ok it seems to be behaving better now, uses up to about 3 GB, but then settles down to 753 MB when it's done scanning. Thanks

**Comment by mvoidex** [comment]
hsdev-0.3.0.0 (not on hackage yet) now uses SQLite to store data, so it uses now much less memory
In my case 8 projects + user-db + global-db takes 40MB of SQLite database.
And about 600MB is for ghc session (check/lint/infer types etc.)

There's a branch of SublimeHaskell with support of new hsdev: https://github.com/SublimeHaskell/SublimeHaskell/commits/hsdev-3

**Comment by moodmosaic** [comment]
That's awesome and I'm looking forward trying it. Is that branch going to be merged into master anytime soon?

**Comment by mvoidex** [comment]
As soon as possible. Currently branch is for test and not backward compatible with previous hsdev, but to merge into master it will be better to support both versions.

**Comment by moodmosaic** [comment]
Is hsdev-0.3.0.0 on Hackage anytime soon then?

**Comment by mvoidex** [comment]
version `hsdev-0.3.0.1` on hackage

**Comment by moodmosaic** [comment]
Awesome! I'll try it soon. 🚀

**Comment by moodmosaic** [comment]
I haven't done any measurements yet, but I can already tell that `hsdev-3.0.3.0` with the `hsdev-3` branch of SublimeHaskell are way faster! :100: :rocket: :+1: :1st_place_medal:

**Comment by moodmosaic** [comment]
So I'm back using `hsdev` and SublimeHaskell! *Thank you* so much for this.

---

Closing this now and looking forward seeing `SublimeHaskell/hsdev-3` being merged into `master`.
