### ISSUE TITLE
cabal.exe: Could not resolve dependencies

### ISSUE THREAD

**Issue by someanon** [mvoidex/hsdev#46]
I'm using Windows 8.1 / Git Bash / Haskell Platform 8.0.2
```
$ cabal install hsdev
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
trying: hsdev-0.2.1.0 (user goal)
trying: ghc-8.0.2/installed-8.0... (dependency of hsdev-0.2.1.0)
next goal: haddock-api (dependency of hsdev-0.2.1.0)
rejecting: haddock-api-2.17.3, haddock-api-2.17.2 (conflict:
ghc==8.0.2/installed-8.0..., haddock-api => ghc>=8.0 && <8.0.2)
rejecting: haddock-api-2.16.1, haddock-api-2.16.0, haddock-api-2.15.0.2,
haddock-api-2.15.0.1, haddock-api-2.15.0 (conflict: hsdev =>
haddock-api>=2.17.0 && <2.18.0)
Dependency tree exhaustively searched.
```

**Comment by lierdakil** [comment]
Haddock-api doesn't support ghc 8.0.2 yet, https://github.com/haskell/haddock/issues/571
Hsdev depends on haddock-api.
It seems ghc guys messed up a bit and rushed 8.0.2 release.

**Comment by mvoidex** [comment]
You ghc is 8.0.2? Unfortunately, hsdev depends on haddock-api, but there's still no haddock-api for ghc-8.0.2

**Comment by someanon** [comment]
thanks guys, i'll try lower version of platform and ghc

**Comment by someanon** [comment]
Works on Haskell Platform 8.0.1 - Installed hsdev-0.2.1.0

**Comment by moodmosaic** [comment]
I can confirm that Haskell Platform 8.0.1 also worked for me in this case.
