### ISSUE TITLE
hsdev ignores cabal-file extensions

### ISSUE THREAD

**Issue by jkeuhlen** [mvoidex/hsdev#49]
Within project.cabal I list out my language extensions that are common across files: 
      library
        hs-source-dirs:      src
        extensions:   RankNTypes

Over in my source code I use a `forall`:
      foo :: forall a . (...) => ...

And hsdev warns: 
Sublime Haskell: hsdev types returns error: ghc error, msg: Illegal symbol '.' in type
Perhaps you intended to use RankNTypes or a similar language
extension to enable explicit-forall syntax: forall <tvs>. <type>
, id: 4

It seems like hsdev is not using the cabal-file language extensions.

**Comment by mvoidex** [comment]
This is old field (stored in `oldExtension` field), you could use `default-extentions` for now.

**Comment by mvoidex** [comment]
Fixed in master
