### ISSUE TITLE
Installation fails on ghc 7.10.2

### ISSUE THREAD

**Issue by lonelyelk** [mvoidex/hsdev#50]
Command `ghc install hsdev` fails with following error:

```
Resolving dependencies...
Configuring hsdev-0.2.2.0...
Building hsdev-0.2.2.0...
Failed to install hsdev-0.2.2.0
Build log ( /Users/kruk/.cabal/logs/hsdev-0.2.2.0.log ):
Configuring hsdev-0.2.2.0...
Building hsdev-0.2.2.0...
Preprocessing library hsdev-0.2.2.0...
[ 1 of 62] Compiling HsDev.Tools.Ghc.Prelude ( src/HsDev/Tools/Ghc/Prelude.hs, dist/build/HsDev/Tools/Ghc/Prelude.o )
[ 2 of 62] Compiling HsDev.Tools.Ghc.MGhc ( src/HsDev/Tools/Ghc/MGhc.hs, dist/build/HsDev/Tools/Ghc/MGhc.o )

src/HsDev/Tools/Ghc/MGhc.hs:31:1: Warning:
    The import of ‘Packages’ is redundant
      except perhaps to import instances from ‘Packages’
    To import instances alone, use: import Packages()
[ 3 of 62] Compiling HsDev.Version    ( src/HsDev/Version.hs, dist/build/HsDev/Version.o )
[ 4 of 62] Compiling HsDev.Tools.Ghc.Compat ( src/HsDev/Tools/Ghc/Compat.hs, dist/build/HsDev/Tools/Ghc/Compat.o )
[ 5 of 62] Compiling System.Directory.Paths ( src/System/Directory/Paths.hs, dist/build/System/Directory/Paths.o )
[ 6 of 62] Compiling System.Directory.Watcher ( src/System/Directory/Watcher.hs, dist/build/System/Directory/Watcher.o )
[ 7 of 62] Compiling HsDev.Util       ( src/HsDev/Util.hs, dist/build/HsDev/Util.o )

src/HsDev/Util.hs:77:19: Not in scope: ‘Dir.isSymbolicLink’
cabal: Error: some packages failed to install:
hsdev-0.2.2.0 failed during the building phase. The exception was:
ExitFailure 1
```

```
ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2
```

**Comment by hvr** [comment]
The issue was already fixed in `master` via d62352c3fe99ee147ab5cfb4e5f05ef678b9a65f

I'm trying to fixup the meta-data on Hackage, but it's a bit more involved because there's almost no upper bounds so I stumble from one compile failure into the next one... :crying_cat_face:

**Comment by hvr** [comment]
@lonelyelk you could try to `cabal update` and retry... it /should/ work now w/ GHC 7.10.*

**Comment by lonelyelk** [comment]
Thank you! It's resolved!

**Comment by mvoidex** [comment]
@hvr, could you explain, how can it be installed with 7.10.3? I get this:

    rejecting: ghc-7.10.3/installed-99f... (conflict: ghc =>
    directory==1.2.2.0/installed-825..., hsdev => directory>=1.2.6.0)

How do you fix it?

**Comment by hvr** [comment]
@mvoidex the latest version doesn't work w/ GHC 7.10.3, however the previous one does, and that's what `cabal install hsdev` will install for you, as that's what the cabal solver will select when using GHC 7.10.3.

Maybe a picture explains this a bit better: http://104.239.175.197:8080/package/hsdev

**Comment by mvoidex** [comment]
@hvr, thanks for explanation! I missunderstood and thought that there's a way to install hsdev-0.2.2.0 with ghc-7.10.*

**Comment by mvoidex** [comment]
@lonelyelk, i've uploaded `hsdev-0.2.2.1`, which is buildable with `ghc-7.10.3`

**Comment by lonelyelk** [comment]
@mvoidex worked like a charm. Thank you!
