### ISSUE TITLE
installing hsdev-0.2.0.0

### ISSUE THREAD

**Issue by nagyf** [mvoidex/hsdev#54]
Hi! 

I'm trying to use [SublimeHaskell](https://github.com/SublimeHaskell/SublimeHaskell) in sublime editor, and it requires hsdev-0.2.0.0.
I've tried to install it with stack but I get weird dependency problems. 
**Note:** I have a completely clean stack installation, without any packages installed. Also I'm on **Windows 10**. Despite the error messages of stack, msys _is_ installed, and it is on the path.

Below you can see the steps I tries

## **1. Tried to install hsdev-0.2.0.0 with stack**

> C:\Users\...>stack install hsdev-0.2.0.0
> Continuing despite missing tool: msys2
> 
> Error: While constructing the build plan, the following exceptions were encountered:
> 
> In the dependencies for hsdev-0.2.0.0:
>     haddock-api must match >=2.17.0 && <2.18.0, but the stack configuration has no specified version
>                 (latest applicable is 2.17.3.1)
>     haskell-src-exts-1.18.2 must match >=1.17.0 && <1.18.0 (latest applicable is 1.17.1)
>     hdocs must match >=0.5.0, but the stack configuration has no specified version (latest applicable is 0.5.2.0)
>     optparse-applicative-0.13.2.0 must match >=0.11 && <0.13 (latest applicable is 0.12.1.0)
>     simple-log-0.5.1 must match ==0.4.* (latest applicable is 0.4.0)
> 
> Recommended action: try adding the following to your extra-deps in C:\sr\global-project\stack.yaml:
> - haddock-api-2.17.3.1
> - hdocs-0.5.2.0

**After adding the recommended dependencies to the global-project/stack.yaml file:**

> Error: While constructing the build plan, the following exceptions were encountered:
> 
> In the dependencies for hsdev-0.2.0.0:
>     haskell-src-exts-1.18.2 must match >=1.17.0 && <1.18.0 (latest applicable is 1.17.1)
>     optparse-applicative-0.13.2.0 must match >=0.11 && <0.13 (latest applicable is 0.12.1.0)
>     simple-log-0.5.1 must match ==0.4.* (latest applicable is 0.4.0)
> 
> Plan construction failed.

## **2. Tried to install the dependencies manually**

> haskell-src-exts-1.17.1 installed successfully, _but_ simple-log did not:
> 
> **C:\Users\...>stack install simple-log-0.4.0**
> Continuing despite missing tool: msys2
> 
> Error: While constructing the build plan, the following exceptions were encountered:
> 
> In the dependencies for simple-log-0.4.0:
>     directory-1.3.0.0 must match >=1.2 && <1.3 (latest applicable is 1.2.7.1)
> 
> Plan construction failed.
> 

> **C:\Users\...>stack install directory-1.2.7.1**
> Continuing despite missing tool: msys2
> directory-1.2.7.1: download
> directory-1.2.7.1: configure
> Package directory uses a custom Cabal build, but does not use a custom-setup stanza
> Not using the explicit setup deps approach based on configuration
> Strongly recommend fixing the package's cabal file
> directory-1.2.7.1: build
> Package directory uses a custom Cabal build, but does not use a custom-setup stanza
> Not using the explicit setup deps approach based on configuration
> Strongly recommend fixing the package's cabal file
> directory-1.2.7.1: copy/register
> Package directory uses a custom Cabal build, but does not use a custom-setup stanza
> Not using the explicit setup deps approach based on configuration
> Strongly recommend fixing the package's cabal file
> Package directory uses a custom Cabal build, but does not use a custom-setup stanza
> Not using the explicit setup deps approach based on configuration
> Strongly recommend fixing the package's cabal file

> **C:\Users\...>stack install simple-log-0.4.0**
> Continuing despite missing tool: msys2
> 
> Error: While constructing the build plan, the following exceptions were encountered:
> 
> In the dependencies for simple-log-0.4.0:
>     directory-1.3.0.0 must match >=1.2 && <1.3 (latest applicable is 1.2.7.1)
> 
> Plan construction failed. 
> 

**And now I'm stuck, do you have any suggestions?**

**Comment by mvoidex** [comment]
SublimeHaskell accepts hsdev-0.2.2.2 (and it's preferred)

I'm not familiar with stack, @bscottm, could you help? Is there a way to install hsdev with stack?
As i can see, latest version on hackage is [hsdev-0.2.1.0](https://www.stackage.org/nightly-2017-01-17/package/hsdev-0.2.1.0)
I'm not sure why there's no hsdev for ghc-8.0.1, I'll try to look into it this weekend

You can also install hsdev with cabal (cabal install hsdev) with ghc-7.10.* or ghc-8.0.1 (not 8.0.2!)

**Comment by nagyf** [comment]
I'm trying to install sublimehaskell through Package Control, and I get the following error in sublime 3:

> SublimeHaskell: hsdev version is incorrect: 0.2.2.2
> Required version: >= 0.2.0.0 and < 0.2.1.0
> Update it by running 'cabal update' and 'cabal install hsdev'
> 
> To supress this message and disable hsdev set 'enable_hsdev' to false

Maybe I should try to install the plugin manually from github master branch?

**Comment by mvoidex** [comment]
Oh, I see. We switched sublimehaskell to new release strategy based on tags. Seems, that there were no releases for hsdev ≥ 0.2.1.0.

You can then try install [hsdev-0.2.1.0](https://www.stackage.org/lts-6.30) from LTS-6.3.0 (ghc-7.10.3) or with cabal

> Maybe I should try to install the plugin manually from github master branch?

This may also work

**Comment by mtolly** [comment]
You're probably better off using the newer version like you said, but here's a working install with stack for the older version if you want.

1. `stack unpack hsdev-0.2.0.0`, then `cd hsdev-0.2.0.0`

2. Make the following `stack.yaml` inside:

```
resolver: lts-6.30
packages:
- '.'
```

3. `stack install` (if it says you don't have the right GHC, `stack setup` first)

**Comment by bscottm** [comment]
@mvoidex: Would it help if I crafted a push request for my stack.yaml files? hsdev will build with 8.0.2, but it doesn't execute correctly. OTOH, hsdev will build with GHC 7.10.3 and 8.0.1.

**Comment by nagyf** [comment]
@mvoidex @mtolly Thank you guys, great support.
I solved my problem, based on your suggestions, by cleaning up my stack installation completely (just for sure...) and setting the ghc to version 7.10.3 (`stack setup ghc-7.10.3`), also the resolver in the global stack config to lts-6.30.
This way I could easily build hsdev with stack, SublimeHaskell now works like a charm :)

I didn't want to experiment with 8.0.1, I'm still a beginner in haskell, who don't even knows what's the difference between the 2 major versions :)

**Comment by bscottm** [comment]
@mvoidex: I should send you a pull request with my three `stack.yaml`-s for each of the 6, 7, and 8 resolvers.
