### ISSUE TITLE
Fails to load interface for packages included in cabal file

### ISSUE THREAD

**Issue by jkeuhlen** [mvoidex/hsdev#59]
@mvoidex : Opening new issue here as requested. 

Referencing : https://github.com/SublimeHaskell/SublimeHaskell/issues/324#issuecomment-294188292

Here is a copy of my simple code repository: https://github.com/jkeuhlen/haskellscratch

I'm running `hsdev` version 0.2.3.1 and SublimeHaskell version 1.2.1

**Comment by bscottm** [comment]
@mvoidex: "Me too!" Specifically, it's `Data.Text` that's the problem on 0.2.3.2 (and that really hoses up generating completions -- yeah, I'm at the point of revamping how that works...)

[st3proj.zip](https://github.com/mvoidex/hsdev/files/988782/st3proj.zip)

**Comment by bscottm** [comment]
@mvoidex: Never mind. Not sure how the compile went sideways, but a complete deletion of all cabal directories and related packages and a complete recompile later, and it works. Seems awfully fragile somewhere.

Back into another issue: HLint.hs is not found (hlint-2.0.6). Seems like `hsdev` catches someone else's exception and then unwinds the stack prematurely.

**Comment by mvoidex** [comment]
Seems to be fixed in master
