### ISSUE TITLE
hsdev and stack

### ISSUE THREAD

**Issue by iamrecursion** [mvoidex/hsdev#63]
I'm currently doing some digging around SublimeHaskell/SublimeHaskell/issues/318, and the fact that `hsdev` cannot be built for any of the current (or older) stackage snapshots is a bit of a blocker on the work.

Would you object to a pull request that updates `hdsev` and its dependency bounds to be in line with stackage? I do realise that getting `hsdev` on stackage requires additional work on your behalf, but it would bring significant benefits for the `SublimeHaskell` ecosystem. You likely already know, but more information can be found for [stackage](https://github.com/fpco/stackage) and the [stackage maintainers agreement](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md).

I would offer to maintain the package boundaries for stackage myself, but I realise that I'm somewhat of an unknown quantity at this point, and you would likely be wary of giving me contributor access to the `hsdev` repo.

**Comment by mvoidex** [comment]
Sorry, I haven't noticed, that hsdev is not on stackage.
I've uploaded `hsdev-0.2.5.0` with updated constraints and created PR: https://github.com/fpco/stackage/pull/2545

**Comment by iamrecursion** [comment]
Brilliant, thanks! Once that gets updated into `nightly` it should unblock the `SublimeHaskell` work.

**Comment by mvoidex** [comment]
I'll try to take care on hsdev's availability on stackage, but feel free to ping me if something is broken.

**Comment by iamrecursion** [comment]
Will do! Thanks for sorting this so quickly.

**Comment by iamrecursion** [comment]
Might need to check that PR. Seems the Travis build has failed.

**Comment by mvoidex** [comment]
I've uploaded `hsdev-0.2.4.0` first with only deps for `text-region` updated
And there were three errors:

* hformat-0.3.0.0 (mvoidex) is out of bounds for hsdev - fixed
* simple-log-0.9.2 (mvoidex) is out of bounds for hsdev - fixed
* hsyslog-4 (peti) is out of bounds for hdaemonize - not mine

**Comment by iamrecursion** [comment]
Sounds good. Hopefully that should land a fix soon as well. It'd be great to get this into `nightly` this week so that it gets cut into the next set of `lts` releases for `ghc-8.2.x` when that lands.

**Comment by iamrecursion** [comment]
Just bumping this as it's out of bounds for the latest `stack` nightly with `ghc-8.2.1`.

**Comment by mvoidex** [comment]
https://github.com/fpco/stackage/pull/2765

**Comment by iamrecursion** [comment]
Great, thanks!

**Comment by mvoidex** [comment]
There are still no actual haddock for ghc-8.2.1

**Comment by iamrecursion** [comment]
How annoying. Hopefully that gets sorted soon.

**Comment by iamrecursion** [comment]
I think there is now a version of `haddock-library` available on `nightly`. Is it possible to try and get this working again?

**Comment by rikvdkleij** [comment]
I try to build `hsdev-2.5.1` with Stack LTS 10.0 and get this error:
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hsdev-0.2.5.1:
    haddock-api must match >=2.18.0 && <2.19.0, but the stack configuration has no specified version (latest matching
                version is 2.18.1)
    hdocs must match >=0.5.0, but the stack configuration has no specified version (latest matching version
          is 0.5.2.1)
needed since hsdev is a build target.

Some potential ways to resolve this:

  * Recommended action: try adding the following to your extra-deps in /Users/rik/.stack/global-project/stack.yaml:

- haddock-api-2.18.1
- hdocs-0.5.2.1

  * Set 'allow-newer: true' to ignore all version constraints and build anyway.

  * You may also want to try using the 'stack solver' command.

Plan construction failed.
```

Is is possible to reduce the number of external dependencies so `hsdev` would be easier to build and get in Stackage LTS and to hold in future Stackage LTS? I'm mainly interested in type and location info so I do need not all the features of `hsdev`. Some background: I'm considering to replace Intero for the IntelliJ-Haskell plugin and `hsdev` would be an option but it must be easily to build.

**Comment by mvoidex** [comment]
Breaking dependency is `haddock-api`, which was removed from stackage due to dependency of `Cabal >= 2`. It's used to get docs for installed modules and for sources.

I've added flag `docs`. If disabled, `haddock-api` and `hdocs` not required.
There are also several stack configs:

- `stack.yaml` - build with `lts-10.3`
- `stack-no-docs.yaml` - build with `lts-10.3` and `docs` disabled, thus no `haddock-api`/`hdocs` deps
- `nightly.yaml` - build with nightly resolver
- `nightly-no-docs.yaml` - with nightly and no `docs`

**Comment by mvoidex** [comment]
Also, uploaded [hsdev-0.3.0.0](https://hackage.haskell.org/package/hsdev-0.3.0.0)

**Comment by iamrecursion** [comment]
Hopefully it can hit stackage nightly soon!

**Comment by moodmosaic** [comment]
Is hsdev-0.3.* going to be on Stackage?

Currently I see only up to version 0.2.5.1. ([Snapshots containing hsdev](https://www.stackage.org/package/hsdev/snapshots))

**Comment by moodmosaic** [comment]
FWIW, if you want to build hsdev-0.3.0.3 with Stack, without haddock/hdocs dependency, do

```
stack build hsdev-0.3.0.3 --flag hsdev:-docs
```

**Comment by iamrecursion** [comment]
I can't get that to work on nightly. Which stackage release are you using?

**Comment by moodmosaic** [comment]
resolver: lts-10.3

**Comment by iamrecursion** [comment]
Ah okay. It's out of bounds on `nightly`.

**Comment by mvoidex** [comment]
there's [nightly.yaml](https://github.com/mvoidex/hsdev/blob/master/nightly.yaml) for nightly stack

**Comment by iamrecursion** [comment]
How would I use that `.yaml` with `stack install`?

**Comment by moodmosaic** [comment]
Also, it looks like hsdev-0.3.0.3 and SublimeHaskell/hsdev-3 no longer work together as per https://github.com/SublimeHaskell/SublimeHaskell/issues/399/.

**Comment by mvoidex** [comment]
> How would I use that .yaml with stack install?

```
stack build --copy-bins --stack-yaml nightly.yaml
```

**Comment by iamrecursion** [comment]
That works! Thanks!
