### ISSUE TITLE
whois / file not found

### ISSUE THREAD

**Issue by Me163** [mvoidex/hsdev#65]
I've been trying to get SublimeHaskell working, but have been having issues. After noticing some hsdev related errors in the console output, I decided to try the corresponding hsdev commands from the CLI.

Here is one example, for which I get the same result in the CLI as I do in the Sublime console:

```
$ ~/.cabal/bin/hsdev start
Server started at port 4567
$ ~/.cabal/bin/hsdev whois main -f ./areaUnderCurve.hs
{"error":"other error","msg":"File '/Users/Ken/Documents/HaskellExperiments/area/areaUnderCurve.hs' not found"}
$ ls ./areaUnderCurve.hs 
./areaUnderCurve.hs
```

Any ideas on how this can happen? Apologies if I'm doing something wrong, I'm extremely new to Haskell and its toolset.

If it matters, this is on macOS 10.12.5.

**Comment by mvoidex** [comment]
You should first scan your files, for example (use one of):

    $ hsdev scan --path /path/to/smth/HaskellExperiments  # scan path
    $ hsdev scan --project /path/to/MyHaskellProject  # scan project
    $ hsdev scan --file /path/to/File.hs  # scan standalone file (non-project)
