### ISSUE TITLE
Are ghc-options getting ignored?

### ISSUE THREAD

**Issue by moodmosaic** [mvoidex/hsdev#72]
I currently have

```
ghc-options:
  -Wall
```

in my .cabal file, and I've made some warnings show up on purpose when running `stack build`:

```
nikos@ubuntu:~/Downloads/ark-gdax$ stack build
ark-gdax-0.1: build (exe)
Preprocessing executable 'ark-gdax' for ark-gdax-0.1..
Building executable 'ark-gdax' for ark-gdax-0.1..
[1 of 1] Compiling Main             ( exe/Main.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/ark-gdax/ark-gdax-tmp/Main.o )

/home/nikos/Downloads/ark-gdax/exe/Main.hs:15:1: warning: [-Wunused-imports]
    The import of ‘Data.Map’ is redundant
      except perhaps to import instances from ‘Data.Map’
    To import instances alone, use: import Data.Map()
   |
15 | import           Data.Map                      (Map)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/nikos/Downloads/ark-gdax/exe/Main.hs:16:1: warning: [-Wunused-imports]
    The qualified import of ‘Data.Map’ is redundant
      except perhaps to import instances from ‘Data.Map’
    To import instances alone, use: import Data.Map()
   |
16 | import qualified Data.Map                      as Map
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/nikos/Downloads/ark-gdax/exe/Main.hs:24:5: warning: [-Wunused-top-binds]
    Defined but not used: ‘messageId’
   |
24 |     messageId :: Text
   |     ^^^^^^^^^
```

However, I see none of those warnings from inside Sublime Text.―I'm using `hsdev-0.3.0.3` with the `hsdev-3` branch of SublimeHaskell.

**Comment by moodmosaic** [comment]
OK, it was the *SublimeHaskell: Check and Lint* command.

**Comment by moodmosaic** [comment]
Hmm, sometimes I do get the warnings from inside Sublime Text and sometimes I don't.

**Comment by moodmosaic** [comment]
This looks more like a stack issue...

`stack build` shows no warnings either, unless I do a `git clean -dxf` so that the `.stack-work` folder is deleted. Then after a `stack build` the warnings are back again in both the console and the Sublime Text...

**Comment by mvoidex** [comment]
Calling check again doesn't force reload modules to be faster. But as result secondary check to unchanged module won't produce warnings.

**Comment by moodmosaic** [comment]
I think it's similar with `stack build` as well. Calling `stack build` again is faster, but yields no warnings.
