### ISSUE TITLE
Thank you for hsdev

### ISSUE THREAD

**Issue by moodmosaic** [mvoidex/hsdev#73]
I just wanted to say a *BIG* THANK YOU for all the work you (and the contributors) have been putting on hsdev and SublimeHaskell.

It's really getting better and better, specially with hsdev-3.* and the hsdev-3 branch in SublimeHaskell. I'm almost about to ditch all other 'modern' text editors and stay with Sublime Text, hsdev, and SublimeHaskell.

The only reason I was using other text editors was because hsdev/SublimeHaskell has been a bit slow and hungry in terms of memory.―This is no longer the case :tada: :balloon: :100: :rocket: :1st_place_medal:

**Comment by moodmosaic** [comment]
:heart:

**Comment by mvoidex** [comment]
Thanks :)

**Comment by moodmosaic** [comment]
We (hsdev users) should all be adding a `<3` here every time we're extremely happy with hsdev. So...

:heart:

**Comment by moodmosaic** [comment]
Wish I could buy you a beer (or I'd rather say a 6-pack, 99-pack!) Thanks once again for all the great work on this. It's still the most reliable tool for me (on fairly-sized multi-project Haskell codebases).

**Comment by mvoidex** [comment]
Nice to hear, thank you :)

To my sorrow I have not enough time to fix all issues and implement planned features :(

**Comment by moodmosaic** [comment]
That's totally fine and understandable. :100:
