### ISSUE TITLE
can't install 0.3.1.2 with stack or cabal

### ISSUE THREAD

**Issue by eflister** [mvoidex/hsdev#80]
with cabal:
```
[13 of 76] Compiling HsDev.Project.Compat ( src/HsDev/Project/Compat.hs, dist/build/HsDev/Project/Compat.o )

src/HsDev/Project/Compat.hs:12:1: error:
    Could not find module ‘Distribution.PackageDescription.Parse’
    Perhaps you meant
      Distribution.PackageDescription.Parsec (from Cabal-2.2.0.0)
      Distribution.PackageDescription.Check (from Cabal-2.2.0.0)
      Distribution.PackageDescription.Quirks (from Cabal-2.2.0.0)
    Use -v to see a list of the files searched for.
   |
12 | import Distribution.PackageDescription.Parse
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
in stack, haskell-names and hlint need different haskell-src-exts
```
In the dependencies for haskell-names-0.9.1:
    haskell-src-exts-1.18.2 from stack configuration does not match >=1.20 && <1.21 (latest matching version is 1.20.2)
  
In the dependencies for hlint-1.9.41:
    haskell-src-exts-1.20.2 from stack configuration does not match >=1.18 && <1.20 (latest matching version is 1.19.1)
```

**Comment by moodmosaic** [comment]
Not really an issue. Make sure to add those in your `stack.yaml`:

```
extra-deps:
- haskell-src-exts-1.18.2
- haskell-src-exts-1.20.2
```

**Comment by mvoidex** [comment]
Updated `stack.yaml` in bf6aaac822197dd218fd8600c8e48527e1799073, also uses LTS 11.2 now

**Comment by bscottm** [comment]
@moodmosaic, @eflister: `stack.yaml` corresponds to GHC 8.4 (a moving target), whereas you probably want to use either `stack-ghc-8.2.2.yaml` or `stack-ghc-8.0.2.yaml`, depending on which GHC you're using.

    stack --stack-yaml=stack-ghc-8.2.2.yaml build

There are a couple of patch sets that I need to publish on the SublimeHaskell `hsdev-3` branch that allow you to set extra arguments in the `hsdev` backend to select the appropriate `stack.yaml`.

**Comment by mvoidex** [comment]
Recent version now can be installed from cabal or with `stack install` from sources.
