### ISSUE TITLE
Option to disable coloredLine/ANSI terminal output

### ISSUE THREAD

**Issue by bscottm** [mvoidex/hsdev#81]
Need an option to disable colored ANSI terminal output, especially for SublimeText's console, where the escape sequences are visually distracting.

It's probably fine for something like `hsdev listen`. For the primary use case, ST3, it's going to be a problem for user issue reports.

**Comment by mvoidex** [comment]
Uploaded [hsdev-0.3.1.3](https://hackage.haskell.org/package/hsdev-0.3.1.3) with `--no-color` flag

**Comment by moodmosaic** [comment]
I just updated to hsdev-0.3.1.3 but still see garbage. Perhaps I need to specify the `--no-color` flag somewhere(?) /cc @bscottm 

![image](https://user-images.githubusercontent.com/287532/37893584-26f168e4-30e4-11e8-824d-e3b818308821.png)

**Comment by moodmosaic** [comment]
I just saw https://github.com/SublimeHaskell/SublimeHaskell/pull/386/commits/1e8d2e04d27d45509a7e7de6751bbe2314eff4e5, so I'll pull the latest and retry.
