### ISSUE TITLE
Add build flag to disable `hlint` dependency

### ISSUE THREAD

**Issue by mvoidex** [mvoidex/hsdev#84]
Allow `hsdev` be built without `hlint` dependency.

Related to #76

**Comment by brodeuralexis** [comment]
Moreover, `hlint` fails to build due to an ambiguous occurence of `escapeHTML` at version `2.0.15`.  It was fixed in versions greater than `2.1.`, but the `hsdev.cabal` prevents newer versions from being used, so `cabal install hsdev` doesn't work here.

**Comment by mvoidex** [comment]
Added in [hsdev-0.3.2.0](https://github.com/mvoidex/hsdev/tree/hsdev-0.3.2.0) branch
