### ISSUE TITLE
incomplete response from `complete`

### ISSUE THREAD

**Issue by bscottm** [mvoidex/hsdev#86]
I'm trying to diagnose a SH freeze that happens when invoking the `complete` command. However, the command line version is hosed:

    % stack --stack-yaml=stack-ghc-8.2.2.yaml exec -- hsdev complete --file ~/play/emuwork/src-emubase/Machine/Types.hs
    Missing:

    Usage: hsdev complete [-w|--wide] (-f|--file path)
      show completions for input

Currently, `complete` will cause SH to freeze for 5 minutes (the default timeout for `hsdev` responses). Would like to figure out why. The JSON is similar to the command line:

    HsDevClient.call[6] cmd 'complete' opts
    {'command': 'complete',
     'file': '/Users/me/play/emuwork/src-emubase/Machine/Types.hs',
     'id': '6',
     'no-file': True,
     'prefix': '',
     'wide': False}

(BTW: I propagated the new and changed `hsdev` backend methods to the `NoneBackend` and the `HaskellBackend` classes. Really should consider running `pylint` after you hack on SH. You would be surprised at the number of people who actually use the "none" backend, which makes its functionality very important. As important as `hsdev`. :-)

**Comment by bscottm** [comment]
The problem manifests itself as a short read on the SH client -- SH sees an incomplete (short) response. Somewhat wondering if the socket needs to be forcibly flushed. I'll experiment and report back.

**Comment by mvoidex** [comment]
> However, the command line version is hosed
`complete` command expects prefix, but you can pass empty one:

    hsdev complete "" --file <file>

Yes, it's slow. I'll try to figure out, what's wrong

**Comment by bscottm** [comment]
@mvoidex: I've captured a packet trace between SH and `hsdev` and confirmed that `complete` does send an incomplete response. I don't think the problem is `hsdev` itself because `wireshark` does show that `hsdev` stops sending data, with subsequent "invalid file descriptor messages" in `stderr`. That would lead me to conclude that the `network-2.6.3.5` package is reaping socket/file descriptors before their time or that the `sendAll` function is misimplemented or something else funky is going on in `encode`.

Doesn't matter if `hsdev` is built with 8.0.2 or 8.2.2.

**Comment by mvoidex** [comment]
Is it fixed with #87?

**Comment by bscottm** [comment]
Unable to stall `hsdev`... so far.

**Comment by mvoidex** [comment]
Try to install from `master` with `stack.yaml`
Or from [ghc-8.4.2](https://github.com/mvoidex/hsdev/tree/ghc-8.4.2) with `stack.yaml` or `nightly.yaml`
